encoding: utf-8

# url
url: "raceup.it"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /news/

# site
title: Race UP Team
email: info@raceup.it
description: Race UP is the FSAE team of the University of Padova. Since 2006 we build one of the fastest racing car in FSAE competitions.
keywords: "raceup unipd fsae"

# social
twitter_username: RaceUpTeam

# plugins
plugins:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["it", "en"]

# to avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["js", "images", "css", "scripts", "tmp"]

# exclude from webpage
exclude: ["run_site.sh", "upload_site.sh", "imgopt.sh", "scripts", "tmp", "CHANGELOG.md", "README.md", "LICENSE", "TODO.md"]

# build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# post cateogories
collections:
  articles:
    output: true
    permalink: /:year/:month/:day/:title
  posts:
    output: true
    permalink: /:year/:month/:day/:title
